#!/usr/bin/env ruby

# frozen_string_literal: true

changed_files = `git status --porcelain`.split(/\n/)

staged_files = changed_files.map do |file|
  /^[AM].\s(?<filename>.+)$/ =~ file # Find added or modified files that are staged
  filename
end.compact

staged_ruby_files = staged_files.select do |file_name|
  file_extension = File.extname(file_name)
  file_extension == '.rb' || file_extension == '.rake'
end

exit(0) if staged_ruby_files.empty?

success = system(%(rubocop #{staged_ruby_files.join(' ')}))

exit(0) if success

puts 'Rubocop generated warnings on added/modified files.  Commit hook failed.'
exit(1)
