#!/usr/bin/env ruby

ADDED_OR_MODIFIED = /^\s*(A|M)+/.freeze

changed_files = `git status --porcelain`.split(/\n/)
unstaged_files = `git ls-files -m`.split(/\n/)

changed_files = changed_files.select { |f| f =~ ADDED_OR_MODIFIED }
changed_files = changed_files.map { |f| f.split(" ")[1..-1].join(' ') }

changed_files -= (unstaged_files - changed_files)

changed_files = changed_files.select do |file_name|
  File.extname(file_name) == ".rb" || File.extname(file_name) == ".rake"
end

changed_files = changed_files.join(" ")

exit(0) if changed_files.empty?

success = system(%(rubocop #{changed_files}))

exit(0) if success

puts 'Rubocop generated warnings on added/modified files.  Commit hook failed.'
exit(1)
