#!/usr/bin/env ruby

changed_files = `git status --porcelain`.split(/\n/)
unstaged_files = `git ls-files -m`.split(/\n/)

changed_files = changed_files.map do |file|
  /^\s*[AM]+\s+(?<filename>.+)$/ =~ file  # Find added or removed files
  filename
end.compact

changed_files -= (unstaged_files - changed_files)

changed_files = changed_files.select do |file_name|
  File.extname(file_name) == ".rb" || File.extname(file_name) == ".rake"
end

changed_files = changed_files.join(" ")

exit(0) if changed_files.empty?

success = system(%(rubocop #{changed_files}))

exit(0) if success

puts 'Rubocop generated warnings on added/modified files.  Commit hook failed.'
exit(1)
