inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/*
    # GitHub actions installs gems in the vendor directory, which causes rubocop to try
    # and cop our gems. We don't want it to.
    - vendor/**/*
    - 'config/initializers/backtrace_silencers.rb'
    - 'config/environments/*'
    - 'bin/*'
    - 'config/application.rb'

# The cop is meant to enforce conventions regarding variables containing numbers
# However in 0.43.0 it is bugged. Both changed on master and disabled by default
# The exclusions don't even get added to the rubocop_todo properly!
Naming/VariableNumber:
  Enabled: false
Rails:
  Enabled: true

# Enforces 1234565789 as 123_456_789: While nice when dealing with actual big
# numbers, we're more likely to see it shout at us about barcodes.
Style/NumericLiterals:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'lib/tasks/*'

Layout/LineLength:
  Max: 100
  Exclude:
    - 'lib/tasks/*'
    # TODO: I have tried to add this to rubocop todo but it is causing all sorts of issues
    # The maximum line length is 157.
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 12
  Exclude:
    - 'db/migrate/*'

Metrics/ClassLength:
  Max: 100
  Exclude:
    - 'app/models/pacbio/well.rb'

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Style/ClassAndModuleChildren:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: space

Naming/FileName:
  Enabled: false

Style/NumericPredicate:
  AutoCorrect: false
  Enabled: true
  EnforcedStyle: comparison

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/CaseEquality:
  Exclude:
    - 'db/migrate/*'

Rails/EnvironmentVariableAccess:
  AllowReads: true

# Don't agree with this cop. We sometimes need multiple lets and some do make sense.
RSpec/IndexedLet:
  Enabled: false

# The work needed to try and make this work is brutal. We would need to reimplement
RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/messages/broker_spec.rb'

RSpec/MessageSpies:
  EnforcedStyle: receive
