language: ruby
dist: xenial
sudo: required
before_script:
- cp config/database.yml.example config/database.yml
- cp config/mailer.yml.example config/mailer.yml
- bundle exec rake db:reset
- bundle exec rake db:setup
script:
- bundle exec rspec
- bundle exec rubocop
before_deploy: "./compile-build"
deploy:
  provider: releases
  api_key:
    secure: CfZ2EH5ESqW+4C6zJLSV7OM25BTb9SGM7/gSBCyiD9U7rZxllulmPj8A8Tt4yPm8mA4hmkz/P4Gx6OydqgYYgXhuiPwyQSOQIOhWI84rdy/ReFNVvN24YBSJKBvQEI9GiLEr9I07DX3wX8CuU+82sZ067z6xaFEye0Cwm0NSy6MuPVggIhKlFWtEJm1FpbcdCi4zFhQIDM6H6B29AQ/1ElEfPIZSAwiVG5FemH3N9yFLXdY8y8y6iiI781TzBoufwf4/ohUZKN77LIlhCuvTCMRrL7kMtOAM9xp+5F9X5WuUIHlVEmKpXqNiJeuQhhWvVaHqEOGLz5ir3SXgwFmcmGxdXEHjqVZYCi8rLzW3tg/LOjnTmk1RDvY39r0eyMnirhO+5hDQHizICf5cr0hBWGDfkIBUmjL1IV0O0jwKgdYaUvauv0+Cb2vBdKSbiH7y73ZNtmT5UBhBc9zVZKETquiJNZhtywgNj0/x75X8kGPL0UKBUzkF4A1Am/czmQwFrf0xZRXV4HfITqDMitZciW4mgJ56JvATBxXpHM2xEbJaGzFriJAkGv15mfRbSNacLh3Y1m6uB8JDtHqr1TuQ0UegNSZeDF5T64Ek4rV68yBRLAu4+JG0EYWNkvgWN8m9l5bw1J/zQnORkqNlKoVhQFtE99cr8YolnZA+Km9saEQ=
  file: release.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: sanger/traction-service
