#!/bin/bash

set -e
echo 'Generating sha'
git rev-parse HEAD > REVISION
git tag -l --points-at HEAD --sort -version:refname | head -1 > TAG
git rev-parse --abbrev-ref HEAD > BRANCH
echo 'Compiling tar.gz'
tar \
  --exclude='*.swp' \
  --exclude='./.bundle' \
  --exclude='./.git' \
  --exclude='./.gitignore' \
  --exclude='./.rspec' \
  --exclude='./.rubocop*' \
  --exclude='./.tags' \
  --exclude='./.travis.yml' \
  --exclude='./README*' \
  --exclude='./compile-build' \
  --exclude='./coverage' \
  --exclude='./*.sublime-project' \
  --exclude='./log/*' \
  --exclude='./node_modules' \
  --exclude='./spec' \
  --exclude='./tmp' \
  --exclude='./vendor/bundle' \
  --exclude='release.tar.gz' \
  --exclude='./documentation' \
  -zcvf /tmp/release.tar.gz ./
mv /tmp/release.tar.gz ./release.tar.gz
echo 'Release complete!'
echo `pwd`/release.tar.gz
