default: &default
  ont:
    message:
      lims: Traction
      key: oseq_flowcell_run
      fields:
        last_updated:
          type: :constant
          value: Time.current
        experiment_name:
          type: :model
          value: experiment_name
        instrument_name:
          type: :string
          value: GXB02004
        flowcells:
          type: :array
          value: flowcells
          children:
            id_flowcell_lims:
              type: :model
              value: uuid
            instrument_slot:
              type: :model
              value: position
            samples:
              type: :array
              value: requests
              children:
                sample_uuid:
                  type: :model
                  value: external_id
                study_uuid:
                  type: :string
                  value: 468e0cd0-6a9d-11ea-a04f-fa163e68e77d
                tag_identifier:
                  type: :model
                  value: tags.first.group_id
                tag_sequence:
                  type: :model
                  value: tags.first.oligo
                tag_set_id_lims:
                  type: :model
                  value: tags.first.tag_set.id
                tag_set_name:
                  type: :model
                  value: tags.first.tag_set.name
    
    sample_sheet:
      columns:
        flow_cell_id:
          type: :model
          value: flowcell_id
          populate:
            for:
              - :sample
            with: :flowcell
        kit:
          type: :model
          value: pool.kit_barcode
          populate:
            for:
              - :sample
            with: :flowcell
        sample_id:
          type: :model
          value: pool.tube.barcode
          populate:
            for:
              - :sample
            with: :flowcell
        experiment_id:
          type: :model
          value: run.experiment_name
          populate:
            for:
              - :sample
            with: :flowcell
        barcode: 
          type: :model
          value: tag.group_id
          populate:
            for:
              - :sample
            with: :sample
        alias: 
          type: :model
          value: sample.name
          populate:
            for:
              - :sample
            with: :sample
        type:
          type: :model
          value: request.data_type.name
          populate:
            for:
              - :sample
            with: :sample

development: *default
test: *default
uat: *default
training: *default
production: *default