default: &default
  ont:
    message:
      lims: Traction
      key: oseq_flowcell_run
      fields:
        last_updated:
          type: :constant
          value: Time.current
        experiment_name:
          type: :model
          value: experiment_name
        instrument_name:
          type: :model
          value: instrument.name
        run_uuid:
          type: :model
          value: uuid
        flowcells:
          type: :array
          value: flowcells
          children:
            id_flowcell_lims:
              type: :model
              value: uuid
            instrument_slot:
              type: :model
              value: position
            flowcell_id:
              type: :model
              value: flowcell_id
            samples:
              type: :array
              value: libraries
              children:
                sample_uuid:
                  type: :model
                  value: request.sample.external_id
                study_uuid:
                  type: :model
                  value: request.external_study_id
                pipeline_id_lims:
                  type: :model
                  value: request.library_type.name
                requested_data_type:
                  type: :model
                  value: request.data_type.name
                library_tube_uuid:
                  type: :model
                  value: pool.uuid
                library_tube_barcode:
                  type: :model
                  value: pool.tube.barcode
                tag_identifier:
                  type: :model
                  value: tag.group_id
                tag_sequence:
                  type: :model
                  value: tag.oligo
                tag_set_id_lims:
                  type: :model
                  value: tag_set.id
                tag_set_name:
                  type: :model
                  value: tag_set.name
    
    sample_sheet:
      v1:
        columns:
          flow_cell_id:
            type: :model
            value: flowcell_id
            populate:
              for:
                - :sample
              with: :flowcell
          kit:
            type: :model
            value: pool.kit_barcode
            populate:
              for:
                - :sample
              with: :flowcell
          sample_id:
            type: :model
            value: pool.tube.barcode
            populate:
              for:
                - :sample
              with: :flowcell
          experiment_id:
            type: :model
            value: run.experiment_name
            populate:
              for:
                - :sample
              with: :flowcell
          barcode: 
            type: :model
            value: tag_barcode
            populate:
              for:
                - :sample
              with: :sample
          alias: 
            type: :model
            value: sample.name
            populate:
              for:
                - :sample
              with: :sample
          type:
            type: :model
            value: request.data_type.name
            populate:
              for:
                - :sample
              with: :sample

development: *default
test: *default
uat: *default
training: *default
production: *default