default: &default
  pacbio:
    message:
      lims: Traction
      key: pac_bio_run
      fields:
        last_updated:
          type: :constant
          value: Time.current
        id_pac_bio_run_lims:
          type: :model
          value: name
        pac_bio_run_uuid:
          type: :model
          value: uuid
        pac_bio_run_name:
          type: :model
          value: name
        wells:
          type: :array
          value: wells
          children:
            plate_number:
              type: :model
              value: plate.plate_number
            plate_uuid_lims:
              type: :model
              value: plate.uuid
            well_label:
              type: :model
              value: position
            well_uuid_lims:
              type: :model
              value: uuid
            samples:
              type: :array
              value: base_used_aliquots
              children:
                cost_code:
                  type: :model
                  value: source.cost_code
                pac_bio_library_tube_id_lims:
                  type: :model
                  value: used_by.id
                pac_bio_library_tube_uuid:
                  type: :string
                  value: ''
                pac_bio_library_tube_name:
                  type: :model
                  value: source.sample_name
                sample_uuid:
                  type: :model
                  value: source.sample.external_id
                study_uuid:
                  type: :model
                  value: source.external_study_id
                tag_sequence:
                  type: :model
                  value: tag.oligo
                tag_set_id_lims:
                  type: :model
                  value: tag.tag_set.id
                tag_identifier:
                  type: :model
                  value: tag.group_id
                tag_set_name:
                  type: :model
                  value: tag.tag_set_name
                pipeline_id_lims:
                  type: :model
                  value: source.library_type
                pac_bio_library_tube_barcode:
                  type: :model
                  value: used_by.tube.barcode

    # For instructions on structure and syntax, see: 'app/exchanges/README.md'
    sample_sheet:
      v12_revio:
        column_order:
          - Library Type
          - Reagent Plate
          - Plate 1
          - Plate 2
          - Run Name
          - Instrument Type
          - Run Comments
          - Is Collection
          - Sample Well
          - Well Name
          - Movie Acquisition Time (hours)
          - Include Base Kinetics
          - Library Concentration (pM)
          - Polymerase Kit
          - Automation Parameters
          - Adapters / Barcodes
          - Barcode Name
          - Bio Sample Name
        fields:
         _sorted_wells:
          type: :array
          value: sorted_wells # defined in 'app/models/concerns/sample_sheet.rb'
          children:
            Library Type:
              type: :string
              value: Standard
            Reagent Plate:
              type: :model
              value: plate.plate_number
            Plate 1:
              type: :model
              value: sequencing_kit_box_barcode_plate_1
            Plate 2:
              type: :model
              value: sequencing_kit_box_barcode_plate_2
            Run Name:
              type: :model
              value: plate.run.name
            Instrument Type:
              type: :model
              value: plate.run.system_name
            Run Comments:
              type: :model
              value: plate.run.comments
            Is Collection:
              type: :model
              value: collection?
            Sample Well:
              type: :model
              value: position_leading_zero
            Well Name:
              type: :model
              value: tube_barcode
            Movie Acquisition Time (hours):
              type: :model
              value: movie_acquisition_time
            Include Base Kinetics:
              type: :model
              value: include_base_kinetics
            Library Concentration (pM):
              type: :model
              value: library_concentration
            Polymerase Kit:
              type: :model
              value: polymerase_kit
            Automation Parameters:
              type: :model
              value: automation_parameters
            Adapters / Barcodes:
              type: :model
              value: barcode_set
            Bio Sample Name:
              type: :model
              value: bio_sample_name
            samples:
              type: :array
              value: aliquots_to_show_per_row
              children:
                Reagent Plate:
                  type: :parent_model
                  value: plate.plate_number
                Is Collection:
                  type: :model
                  value: collection?
                Sample Well:
                  type: :parent_model
                  value: position_leading_zero
                Barcode Name:
                  type: :model
                  value: barcode_name
                Bio Sample Name:
                  type: :model
                  value: bio_sample_name
      v12_sequel_iie: &v12_sequel_iie
        column_order:
          - Instrument Type
          - Run Name
          - Is Collection
          - Sample Well
          - Sample Name
          - Movie Time per SMRT Cell (hours)
          - Insert Size (bp)
          - SMRTbell Adapter Design
          - Binding Kit Box Barcode
          - Sequencing Kit Box Barcode
          - On-Plate Loading Concentration (pM)
          - DNA Control Complex Box Barcode
          - Run Comments
          - Sample is Barcoded
          - Barcode Name
          - Barcode Set
          - Same Barcodes on Both Ends of Sequence
          - Bio Sample Name
          - Automation Parameters
          - CCS Analysis Output - Include Kinetics Information
          - Loading Target (P1 + P2)
          - Use Adaptive Loading
          - CCS Analysis Output - Include Low Quality Reads
          - Include 5mC Calls in CpG Motifs
          - Demultiplex Barcodes
        fields:
         _sorted_wells:
          type: :array
          value: sorted_wells # defined in 'app/models/concerns/sample_sheet.rb'
          children:
            Instrument Type:
              type: :model
              value: plate.run.system_name
            Run Name:
              type: :model
              value: plate.run.name
            Is Collection:
              type: :model
              value: collection?
            Sample Well:
              type: :model
              value: position_leading_zero
            Sample Name:
              type: :model
              value: tube_barcode
            Movie Time per SMRT Cell (hours):
              type: :model
              value: movie_time
            Insert Size (bp):
              type: :model
              value: insert_size
            SMRTbell Adapter Design:
              type: :model
              value: template_prep_kit_box_barcode
            Binding Kit Box Barcode:
              type: :model
              value: binding_kit_box_barcode
            Sequencing Kit Box Barcode:
              type: :model
              value: plate.sequencing_kit_box_barcode
            On-Plate Loading Concentration (pM):
              type: :model
              value: on_plate_loading_concentration
            DNA Control Complex Box Barcode:
              type: :model
              value: plate.run.dna_control_complex_box_barcode
            Run Comments:
              type: :model
              value: plate.run.comments
            Sample is Barcoded:
              type: :model
              value: sample_is_barcoded
            Barcode Set:
              type: :model
              value: barcode_set
            Same Barcodes on Both Ends of Sequence:
              type: :model
              value: same_barcodes_on_both_ends_of_sequence
            Bio Sample Name:
              type: :model
              value: bio_sample_name
            Automation Parameters:
              type: :model
              value: automation_parameters
            CCS Analysis Output - Include Kinetics Information:
              type: :model
              value: ccs_analysis_output_include_kinetics_information
            Loading Target (P1 + P2):
              type: :model
              value: loading_target_p1_plus_p2
            Use Adaptive Loading:
              type: :model
              value: adaptive_loading_check
            CCS Analysis Output - Include Low Quality Reads:
              type: :model
              value: ccs_analysis_output_include_low_quality_reads
            Include 5mC Calls in CpG Motifs:
              type: :model
              value: include_fivemc_calls_in_cpg_motifs
            Demultiplex Barcodes:
              type: :model
              value: demultiplex_barcodes
            samples:
              type: :array
              value: aliquots_to_show_per_row
              children:
                Is Collection:
                  type: :model
                  value: collection?
                Sample Well:
                  type: :parent_model
                  value: position_leading_zero
                Barcode Name:
                  type: :model
                  value: barcode_name
                Bio Sample Name:
                  type: :model
                  value: bio_sample_name
      v13_revio:
        column_order:
          - Library Type
          - Reagent Plate
          - Plate 1
          - Plate 2
          - Run Name
          - Instrument Type
          - Run Comments
          - Is Collection
          - Sample Well
          - Well Name
          - Movie Acquisition Time (hours)
          - Include Base Kinetics
          - Library Concentration (pM)
          - Polymerase Kit
          - Automation Parameters
          - Indexes
          - Barcode Name
          - Bio Sample Name
          - Insert Size (bp)
          - Use Adaptive Loading
        fields:
         _sorted_wells:
          type: :array
          value: sorted_wells # defined in 'app/models/concerns/sample_sheet.rb'
          children:
            Library Type:
              type: :string
              value: Standard
            Reagent Plate:
              type: :model
              value: plate.plate_number
            Plate 1:
              type: :model
              value: sequencing_kit_box_barcode_plate_1
            Plate 2:
              type: :model
              value: sequencing_kit_box_barcode_plate_2
            Run Name:
              type: :model
              value: plate.run.name
            Instrument Type:
              type: :model
              value: plate.run.system_name
            Run Comments:
              type: :model
              value: plate.run.comments
            Is Collection:
              type: :model
              value: collection?
            Sample Well:
              type: :model
              value: position_leading_zero
            Well Name:
              type: :model
              value: tube_barcode
            Movie Acquisition Time (hours):
              type: :model
              value: movie_acquisition_time
            Include Base Kinetics:
              type: :model
              value: include_base_kinetics
            Library Concentration (pM):
              type: :model
              value: library_concentration
            Polymerase Kit:
              type: :model
              value: polymerase_kit
            Automation Parameters:
              type: :model
              value: automation_parameters
            Indexes:
              type: :model
              value: barcode_set
            Bio Sample Name:
              type: :model
              value: bio_sample_name
            Insert Size (bp):
              type: :model
              value: insert_size
            Use Adaptive Loading:
              type: :string
              value: FALSE
            samples:
              type: :array
              value: aliquots_to_show_per_row
              children:
                Reagent Plate:
                  type: :parent_model
                  value: plate.plate_number
                Is Collection:
                  type: :model
                  value: collection?
                Sample Well:
                  type: :parent_model
                  value: position_leading_zero
                Barcode Name:
                  type: :model
                  value: barcode_name
                Bio Sample Name:
                  type: :model
                  value: bio_sample_name
      # No changes required from v12_sequel_iie, added for consistency
      v13_sequel_iie: *v12_sequel_iie


development: *default
test: *default
uat: *default
training: *default
production: *default
