default: &default
  reception:
    stock_resource:
      message:
        lims: &lims Traction
        key: stock_resource
        fields:
          created_at: &timestamp
            type: :constant
            value: Time.current
          updated_at: *timestamp
          labware_coordinate:
            type: :model
            value: requestable.container_material.container.position
          machine_barcode:
            type: :model
            value: requestable.container_material.container.barcode
          human_barcode:
            type: :model
            value: requestable.container_material.container.barcode
          labware_type:
            type: :model
            value: requestable.container_material.container.labware_type
          stock_resource_id:
            type: :model
            value: requestable.container_material.container.id
          samples:
            type: :array
            value: samples_for_stock_resource
            children:
              sample_uuid:
                type: :model
                value: sample.external_id
              study_uuid:
                type: :model
                value: requestable.external_study_id

    sample:
      message:
        lims: *lims
        key: sample
        fields:
          last_updated: *timestamp
          id_sample_lims:
            type: :model
            value: name
          uuid_sample_lims:
            type: :model
            value: external_id
          name:
            type: :model
            value: name
          public_name:
            type: :model
            value: public_name
          common_name:
            type: :model
            value: species
          priority_level:
            type: :model
            value: priority_level
          sanger_sample_id:
            type: :model
            value: sanger_sample_id
          supplier_name:
            type: :model
            value: supplier_name
          taxon_id:
            type: :model
            value: taxon_id
          donor_id:
            type: :model
            value: donor_id
          country_of_origin:
            type: :model
            value: country_of_origin
          accession_number:
            type: :model
            value: accession_number
          date_of_sample_collection:
            type: :model
            value: date_of_sample_collection
    
    compound_sample:
      message:
        lims: *lims
        key: compound_sample
        fields:
          id:
            type: :model
            value: id
          name:
            type: :model
            value: name
          uuid_sample_lims:
            type: :model
            value: external_id
          component_sample_uuids:
            type: :array
            value: component_samples
            children:
              uuid:
                type: :model
                value: external_id
      


development: *default
test: *default
uat: *default
training: *default
production: *default
