---
default: &default
  sequel_iie:
    name: Sequel IIe
    run:
      smrt_link_versions:
      - v11
      root: true
      children: :plates
      validations:
        limits:
          options:
            attribute: :plates
            minimum: 1
            maximum: 1
        required_attributes:
          options:
            required_attributes:
              - :dna_control_complex_box_barcode
    plates:
      children: :wells
      validate_each: :plate_number
      validations:
        limits:
          attribute: :wells
          options:
            minimum: 1
            maximum: 96
        required_attributes:
          options:
            required_attributes:
              - :plate_number
              - :sequencing_kit_box_barcode
    wells:
      terminator: true
  revio:
    name: Revio
    run:
      smrt_link_versions:
      - v12
    root: true
    children: :plates
    validations:
      limits:
        options:
          attribute: :plates
          minimum: 1
          maximum: 2
    plates:
      children: :wells
      validate_each: :plate_number
      validations:
        required_attributes:
          options:
            required_attributes:
              - :plate_number
              - :sequencing_kit_box_barcode
    wells:
      terminator: true
      validations:
        positions:
          options:
            valid_positions:
            - A1
            - B1
            - C1
            - D1
        combinations:
          options:
            valid_combinations:
            - [A1]
            - [A1,B1]
            - [A1,B1,C1]
            - [A1,B1,C1,D1]
            - [B1]
            - [B1,C1]
            - [B1,C1,D1]
            - [C1]
            - [C1,D1]
            - [D1]

development: *default
test: *default
production: *default
uat: *default
training: *default

