# Automatically generate a release on develop and master

name: Automated release and build of project

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # Runs bundle install and caches gems. See the ruby_test.yml
                            # example if you need more control over bundler.

    - name: Set release version
       run: echo "RELEASE_VERSION=$([ ${GITHUB_REF##*/} = "develop" ] && printf '%s\n' $(cat .release-version)-develop || printf '%s\n' $(cat .release-version))" >> $GITHUB_ENV

    - name: Set up environment
      run: |
        cp config/database.yml.example config/database.yml
        cp config/mailer.yml.example config/mailer.yml
        cp config/bunny.yml.example config/bunny.yml
        cp config/env_constants.yml.example config/env_constants.yml

    - name: Compile Build
      run: ./compile-build

    - name: Create release and upload release.tar.gz
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ env.RELEASE_VERSION }}
        tag_name: v${{ env.RELEASE_VERSION }}
        prerelease: ${{ !(github.ref == 'refs/heads/master') }}
        files: release.tar.gz
        fail_on_unmatched_files: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
