name: Deploy Yard to GitHub Pages

on:
  push:
    branches:
      - 'master'
      - '1394-y24-237*'
  workflow_dispatch:

permissions:
  pages: write      # Allow writing to the GitHub Pages
  id-token: write   # Allow OIDC token to be issued

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Generate Yard documentation
        run: |
          bundle exec yard doc
      
      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Install Python Dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-material

      - name: Generate docs
        run: |
          for dir in documentation/*; do
            if [ -d "$dir" ]; then
              echo "Building documentation in $dir"
              mkdocs build
              
              # Define the target directory where you want to copy the site content
              target_directory="doc/$dir"
              mkdir -p $target_directory
              cp -r $dir/site/* $target_directory/
            fi
          done

      - name: Upload artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: doc  # Path to the folder containing the Yard documentation (default is 'doc')

  deploy:
    runs-on: ubuntu-latest
    needs: build  # The deploy job will only run if the build job is successful

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4