name: Ruby Tests

env:
  TZ: Europe/London

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        # Use the Mysql docker image https://hub.docker.com/_/mysql
        image: mysql:8.0
        ports:
         - 3306 # Default port mappings
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        env:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_ROOT_PASSWORD: ''
            MYSQL_DATABASE: traction_service_test

    steps:
      - name: Checkout Repository
        uses: sanger/.github/.github/actions/setup/checkout@master

      - name: Setup Ruby
        uses: sanger/.github/.github/actions/setup/ruby@master

      - name: Set up environment
        env:
          DBPORT: ${{ job.services.mysql.ports[3306] }}
        run: |
          cp config/database.yml.example config/database.yml
          cp config/mailer.yml.example config/mailer.yml
          cp config/bunny.yml.example config/bunny.yml
          bundle exec rake db:reset

      - name: Run tests
        env:
          DBPORT: ${{ job.services.mysql.ports[3306] }}
        run: bundle exec rake
